epochs: 250  # total train epochs
per_batch_size: 2  # 16 * 8 = 128
img_size: 640
iou_thres: 0.7
conf_free: True
sync_bn: True
opencv_threads_num: 0  # opencv: disable threading optimizations

network:
  model_name: yolov8
  nc: 5  # number of classes
  reg_max: 16

  stride: [8, 16, 32]

  # YOLOv8.0n backbone
  backbone:
    # [from, repeats, module, args]
    - [-1, 1, ConvNormAct, [64, 3, 2]]  # 0-P1/2
    - [-1, 1, ConvNormAct, [128, 3, 2]]  # 1-P2/4
    - [-1, 3, C3k2, [256, False, 0.25]]
    - [-1, 1, ConvNormAct, [256, 3, 2]]  # 3-P3/8
    - [-1, 6, C3k2, [256, False, 0.25]]
    - [-1, 1, ConvNormAct, [512, 3, 2]]  # 5-P4/16
    - [-1, 6, C3k2, [512, True]]
    - [-1, 1, ConvNormAct, [1024, 3, 2]]  # 7-P5/32
    - [-1, 3, C3k2, [1024, True]]
    - [-1, 1, SPPF, [1024, 5]]  # 9

  # YOLOv8.0n head
  head:
    - [-1, 1, Upsample, [None, 2, 'nearest']]
    - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
    - [-1, 3, C3k2, [512, False]]  # 12

    - [-1, 1, Upsample, [None, 2, 'nearest']]
    - [[-1, 4], 1, Concat, [1] ]  # cat backbone P3
    - [-1, 3, C3k2, [256, False]]  # 15 (P3/8-small)

    - [-1, 1, ConvNormAct, [256, 3, 2]]
    - [[ -1, 12], 1, Concat, [1]]  # cat head P4
    - [-1, 3, C3k2, [512, False]]  # 18 (P4/16-medium)

    - [-1, 1, ConvNormAct, [512, 3, 2]]
    - [[-1, 9], 1, Concat, [1]]  # cat head P5
    - [-1, 3, C3k2, [1024, True]]  # 21 (P5/32-large)

    - [[15, 18, 21], 1, YOLOv8Head, [nc, reg_max, stride]]  # Detect(P3, P4, P5)
