__BASE__: [
  '../pcb.yaml',
  './hyp.scratch.low.yaml',
  './yolov11-base.yaml'
]

overflow_still_update: False
network:
  depth_multiple: 0.50  # scales module repeats
  width_multiple: 0.50  # scales convolution channels
  max_channels: 1024
