__BASE__: [
  '../pcb.yaml',
  './hyp.scratch.high.yaml',
  './yolov11-base.yaml'
]

overflow_still_update: False
network:
  depth_multiple: 1.00  # scales module repeats
  width_multiple: 1.00  # scales convolution channels
  max_channels: 512
